[versions]
spigot-api = "1.16.5-R0.1-SNAPSHOT"
packetevents = "2.10.0"
luckperms = "5.5"
cmi-api = "9.7.14.3"

[libraries]
spigot-api = { group = "org.spigotmc", name = "spigot-api", version.ref = "spigot-api" }
packetevents = { group = "com.github.retrooper", name = "packetevents-spigot", version.ref = "packetevents" }
luckperms = { group = "net.luckperms", name = "api", version.ref = "luckperms" }
cmi-api = { group = "com.github.Zrips", name = "CMI-API", version.ref = "cmi-api" }